import "./transformationConfig.test.js"
import "./transformationGeneralChoice.test.js"
import "./fiendGiftOfDamnationDialog.test.js"
import "./fiendUnbridledPowerSpellSlotRecoveryDialog.test.js"
import "./hagSpellRecoveryDialog.test.js"
import "./itemInfoDialog.test.js"
import "./feyExhaustionRecoveryDialog.test.js"
